export default [{
    ready: true,
    id: 'cnblogs',
    title: '博客园',
    url: 'https://i.cnblogs.com/EditPosts.aspx?opt=1',
}, {
    ready: true,
    id: 'oschina',
    title: '开源中国',
    url: 'https://www.oschina.net/blog'
}, {
    ready: true,
    id: 'zhihu',
    title: '知乎',
    url: 'https://zhuanlan.zhihu.com/write'
}, {
    ready: true,
    id: 'weixin',
    title: '微信公众号',
    url: 'https://mp.weixin.qq.com'
}, {
    ready: true,
    id: 'csdn',
    title: 'CSDN',
    url: 'https://mp.csdn.net/postedit',
}, {
    ready: true,
    id: 'jianshu',
    title: '简书',
    url: 'https://www.jianshu.com/writer#/',
}, {
    ready: true,
    id: 'douban',
    title: '豆瓣',
    url: 'https://www.douban.com/note/create'
}, {
    ready: true,
    id: 'baijiahao',
    title: '百家号',
    url: 'https://baijiahao.baidu.com/builder/rc/edit?type=news',
}, {
    ready: true,
    id: 'qiehao',
    title: '企鹅号',
    url: 'https://om.qq.com/article/articlePublish',
}, {
    ready: true,
    id: 'toutiaohao',
    title: '头条号',
    url: 'https://mp.toutiao.com'
}, {
    ready: false,
    id: 'wangyihao',
    title: '网易号',
}, {
    ready: false,
    id: 'yidianhao',
    title: '一点号',
}, {
    ready: false,
    id: 'dayuhao',
    title: '大鱼号',
}, {
    ready: false,
    id: 'segmentfault',
    title: '思否',
}, {
    ready: false,
    id: 'wordpress',
    title: 'wordpress',
}, {
    ready: false,
    id: 'qqzone',
    title: 'QQ空间',
    url: 'https://rc.qzone.qq.com/blog/add'
}];